# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d17f606b8f805ebe9997cd385cfe0ac66136850500312f94ad11d0357cf8a10f0a6a4423bc9adc1cf02f7a1a0a69ed04fab505823ee59a8ea5c4a006561991a

test:
  secret_key_base: e4fe73daa9b2a16b323bfa39befa48e4591f46d45e1b5011ebd370c6d12393fc49c386af032c58e9e6e1ebf5d1f52f4889f7971435aae958031d1b9f73eeb140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
